spring:
  application.name: bweng-ws24
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: springuser
    password: springpw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  servlet.multipart.max-file-size: 20MB

minio:
  url: http://localhost
  port: 9000
  user: minioadmin
  password: minioadminpw
  bucket: pictures

security.jwt.secret: averygoodsecretnoonewilleverguessinamillionyears
